spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 0000

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      # show_sql: true
      format_sql: true
logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace #스프링 부트 2.x, hibernate5
